spring:
  datasource:
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        use-new-id-generator-mappings: true
    hibernate:
      naming:
#        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create

logging:
  level:
    org.hibernate.SQL: debug
    org.hivernate.type: trace